version: "2"
services:
  api:
    image: api
    volumes:
      - ./../app:/home/current/app
    command: npm start #top -b #
    environment:
      DEBUG: "true"
      NODE_ENV: development
      APPLICATION_NAME: api
    ports:
      - 3000:3000
