version: "2"
services:
  api:
    image: api
    volumes:
      - ./../app:/home/current/app
    command: npm start #top -b #
    environment:
      DEBUG: "true"
      NODE_ENV: development
      APPLICATION_NAME: api
    ports:
      - 3000:3000

  postgres:
    image: postgres
    environment:
      - LANG=en_US.UTF-8
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=methodfitness
    ports:
      - 5432:5432
  eventstore:
    image: eventstore/eventstore
    ports:
      - 2113:2113
      - 1113:1113
