version: "2"
services:
  api:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ./../app:/home/current/app
    command: npm run docker #top -b #
    ports:
      - 3666:3000
    env_file:
      - ./.env
